networks:
  spring-db: {}

services:
  mariadb:
    # image docker mariadb
    image: 'mariadb:latest'
    environment:
      # root password
      - MARIADB_ROOT_PASSWORD=root
    # creation of the database and the user
    command: --init-file /data/application/initdb.sql
    # mounting the initdb.sql file
    volumes:
      - ./initdb.sql:/data/application/initdb.sql
    # port mapping
    ports:
      - "3306:3306"
    networks:
      - spring-db
